#! /bin/sh

# 
#	ENCERRAR PROCESSOS
#
killall -q sxhkd
killall -q dunst
killall -q polybar
killall -q picom
killall -q mpd
killall -USR1 termite

#
# ESPERAR QUE O PROCESSO ESTEJA ENCERRADO
#
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
while pgrep -u $UID -x sxhkd >/dev/null; do sleep 1; done
while pgrep -u $UID -x dunst >/dev/null; do sleep 1; done
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done


#
#	INICIAR PROCESSOS
#
polybar top &
polybar bottom &
feh --bg-scale ~/Pictures/Backgrounds/dracula.png &
picom --config ~/.config/picom/picom.conf &
sxhkd &
dunst -config ~/.config/dunst/dunstrc &
xsetroot -cursor_name left_ptr &
mpd &
#
#	CONFIGURAÇÃO DA JANELA
#

#NUMEROS DE AREAS DE TRABALHO
bspc monitor -d I II III IV V VI VII VII

#LARGURA DA BORDA
bspc config border_width          2
#LARGURA ENTRE AS JANELAS
bspc config window_gap            8
#RAZÃO DO SPLIT DA JANELA
bspc config split_ratio           0.52

bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

#COR DA JANELA EM FOCO
bspc config focused_border_color  "#6272a4"

#
#	REGRAS DE PROGRAMAS
#

bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a Termite focus=on
bspc rule -a mplayer2 state=floating

bspc config external_rules_command ~/.config/bspwm/external_rules
xbacklight -set 100
